// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMHjk6K-bmJqSvDJi4L5ZOMbh4ZHsBNN4',
    appId: '1:78599419588:web:01df111bd481db68983b91',
    messagingSenderId: '78599419588',
    projectId: 'stopandshop-61e59',
    authDomain: 'stopandshop-61e59.firebaseapp.com',
    storageBucket: 'stopandshop-61e59.appspot.com',
    measurementId: 'G-BR14NCDF3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsf4PNiqPut_icirLAOgKLEpUYnWO5KL8',
    appId: '1:78599419588:android:0d6ed3d2265de27a983b91',
    messagingSenderId: '78599419588',
    projectId: 'stopandshop-61e59',
    storageBucket: 'stopandshop-61e59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWqXzy3bVAJ-hh7mR9gpGzliC9TP4wMeI',
    appId: '1:78599419588:ios:09f2ba11324da90c983b91',
    messagingSenderId: '78599419588',
    projectId: 'stopandshop-61e59',
    storageBucket: 'stopandshop-61e59.appspot.com',
    iosBundleId: 'com.example.stopshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWqXzy3bVAJ-hh7mR9gpGzliC9TP4wMeI',
    appId: '1:78599419588:ios:ca869987ea2056c1983b91',
    messagingSenderId: '78599419588',
    projectId: 'stopandshop-61e59',
    storageBucket: 'stopandshop-61e59.appspot.com',
    iosBundleId: 'com.example.stopshop.RunnerTests',
  );
}
